# Generated by Django 3.2.9 on 2021-11-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('room_type', models.CharField(blank=True, choices=[('NON-SMOKING_KING', 'Non-Smoking King'), ('NON-SMOKING_QUEEN', 'Non-Smoking Queen'), ('NON-SMOKING_DOUBLE_BEDSMOKING_KING', 'Non-Smoking Double Bedsmoking King'), ('SMOKING_QUEEN', 'Smoking Queen'), ('SMOKING_DOUBLE_BED', 'Smoking Double Bed')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AllocatedRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('payment_id', models.CharField(max_length=200)),
                ('allocated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client_assigned', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('room_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.rooms')),
            ],
        ),
    ]
