# Generated by Django 3.2.9 on 2021-11-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(blank=True, choices=[('NON-SMOKING_KING', 'Non-Smoking King'), ('NON-SMOKING_QUEEN', 'Non-Smoking Queen'), ('NON-SMOKING_DOUBLE_BED', 'Non-Smoking Double Bed'), ('SMOKING_KING', 'Smoking King'), ('SMOKING_QUEEN', 'Smoking Queen'), ('SMOKING_DOUBLE_BED', 'Smoking Double Bed')], max_length=255),
        ),
    ]
