# Generated by Django 3.2.9 on 2021-11-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_rooms_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='allocatedrooms',
            name='room_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_room', to='rooms.rooms'),
        ),
    ]
