# Generated by Django 3.2.9 on 2021-11-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20211109_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedrooms',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
