# Generated by Django 3.2.9 on 2021-11-07 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('address', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('city', models.CharField(default='Omaha', max_length=50)),
                ('state', models.CharField(default='NE', max_length=15)),
                ('zipcode', models.CharField(default='00000', max_length=6)),
                ('email', models.EmailField(default='@gmail.com', max_length=100)),
                ('cell_phone', models.CharField(default='(402)000-0000', max_length=13)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
